import "./globals.css";
import type { Metadata } from "next";
import { Gloock, Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import AosProvider from "@/Provider/AosProvider/AosProvider";
import QueryProvider from "@/Provider/QueryProvider/QueryProvider";
import ReduxProvider from "@/Provider/ReduxProvider/ReduxProvider";
import AuthChecker from "@/Provider/AuthChecker/AuthChecker";



const gloock = Gloock({
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-gloock", 
});

const poppins = Poppins({
  weight: ["300", "400","500", "600","700", ], 
  subsets: ["latin"],
  variable: "--font-poppins",
});

// Metadata
export const metadata: Metadata = {
  title: "ESTEVEZ AESTHETICS",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gloock.variable} ${poppins.variable} antialiased`}>
        <QueryProvider>
          <ReduxProvider>
            <AosProvider>
              <Toaster />
              {/* <UseSiteSettings /> */}
              <AuthChecker>{children}</AuthChecker>
            </AosProvider>
            <Toaster />
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
